name: Build iOS Dylib

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        clang -arch arm64 -dynamiclib bypass.c -o bypass.dylib
        ls -la
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: dylib-file
        path: bypass.dylib
