name: Simple Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: |
        clang -arch arm64 -dynamiclib bypass.c -o bypass.dylib
        echo "编译完成！"
        ls -la bypass.dylib
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: compiled-dylib
        path: bypass.dylib
